### ISSUE TITLE
`entry()` API is slow

### ISSUE THREAD

**Issue by LukasKalbertodt** [Amanieu/hashbrown#18]
Hi there!

Yesterday I tried to use this crate as a drop-in replacement for my `FnvHashMap`. Surprisingly, it was not faster, but even a bit slower than my previous version. I profiled a bit and noticed that the `entry()` API of your implementation is probably suboptimal. 

Initially I wrote this:

```rust
map.entry(key).or_insert_with(|| produce_value())
```

To test, I changed it to this:

```rust
if map.contains_key(&key) {
    map[&key]
} else {
    let v = produce_value();
    map.insert(key, v);
    v
}
```

In my particular case, the first version runs in 1.96s while the second runs in 1.74s. In my test case, both branches are taken roughly equally often. The code above is executed 3.6 million times and the hashmap ends up with 1.8 million entries. My key is 12 bytes while the value is 4 bytes large. 

It's a bit strange that the second version is faster since we have to do two lookups (`contains_key` plus either `map[&key]` or `map.insert(key, v)`). And indeed, `FnvHashMap` and the hashmap from `std`) get notably slower in the second version. I mean yeah, the memory used for lookup has probably been properly warmed by `contains_key`, but we still do unnecessary/duplicate work.

---

I also wrote this micro benchmark (since my results above are in a bigger codebase). In the micro benchmark, the key is also 4 bytes, but it already shows what I wanted to show.

<details>

It's basically only two different benchmarks, which are copied to test them with your hash map, `FnvHashMap` and `std::collections::HashMap`.

```rust
#![feature(test)]

extern crate test;

use hashbrown::HashMap as BrownHashMap;
use fnv::FnvHashMap;
use std::collections::HashMap as StdHashMap;
use self::test::{Bencher, black_box};

const SIZE: usize = 1_000_000;

#[bench]
fn brown_entry(b: &mut Bencher) {
    b.iter(|| {
        let mut m = BrownHashMap::with_capacity(SIZE / 3);
        for i in 0..SIZE as u32 {
            black_box(m.entry(i / 3).or_insert(i));
        }
    })
}

#[bench]
fn brown_manual(b: &mut Bencher) {
    b.iter(|| {
        let mut m = BrownHashMap::with_capacity(SIZE / 3);
        for i in 0..SIZE as u32 {
            let key = i / 3;
            let v = if m.contains_key(&key) {
                m[&key]
            } else {
                m.insert(key, i);
                i
            };
            black_box(v);
        }
    })
}

#[bench]
fn fnv_entry(b: &mut Bencher) {
    b.iter(|| {
        let mut m = FnvHashMap::default();
        m.reserve(SIZE / 3);
        for i in 0..SIZE as u32 {
            black_box(m.entry(i / 3).or_insert(i));
        }
    })
}

#[bench]
fn fnv_manual(b: &mut Bencher) {
    b.iter(|| {
        let mut m = FnvHashMap::default();
        m.reserve(SIZE / 3);
        for i in 0..SIZE as u32 {
            let key = i / 3;
            let v = if m.contains_key(&key) {
                m[&key]
            } else {
                m.insert(key, i);
                i
            };
            black_box(v);
        }
    })
}

#[bench]
fn std_entry(b: &mut Bencher) {
    b.iter(|| {
        let mut m = StdHashMap::with_capacity(SIZE / 3);
        for i in 0..SIZE as u32 {
            black_box(m.entry(i / 3).or_insert(i));
        }
    })
}

#[bench]
fn std_manual(b: &mut Bencher) {
    b.iter(|| {
        let mut m = StdHashMap::with_capacity(SIZE / 3);
        for i in 0..SIZE as u32 {
            let key = i / 3;
            let v = if m.contains_key(&key) {
                m[&key]
            } else {
                m.insert(key, i);
                i
            };
            black_box(v);
        }
    })
}
```
</details>

The results are:

```
test brown_entry  ... bench:  15,433,281 ns/iter (+/- 6,619,394)
test brown_manual ... bench:  13,233,574 ns/iter (+/- 4,212,542)
test fnv_entry    ... bench:  45,841,114 ns/iter (+/- 11,072,757)
test fnv_manual   ... bench:  47,913,048 ns/iter (+/- 8,861,713)
test std_entry    ... bench:  69,736,423 ns/iter (+/- 14,587,644)
test std_manual   ... bench:  84,257,629 ns/iter (+/- 17,948,341)
```

So only for `brownhash` the manual version (without `entry()`) is faster, while it's slower for the two other hashmaps (as one would expect).

---

So it would be awesome if the `entry()` API could be improved still. Or is there something about the data structure behind this hashmap that makes it difficult or useless to make the entry APi fast? Thanks!

**Comment by LukasKalbertodt** [comment]
Thanks for the quick reply and fix! 

I just tried my original test with the your `master` branch and indeed, the `entry()` version is faster now :tada: (2.06s vs 2.35s in my original test; test environment is slightly different than in my first post, so those numbers are not comparable). In the test benchmark I posted above, I get the following results now:

```
test brown_entry  ... bench:  10,416,253 ns/iter (+/- 6,420,959)
test brown_manual ... bench:  16,704,658 ns/iter (+/- 8,961,890)
test fnv_entry    ... bench:  43,876,666 ns/iter (+/- 27,247,781)
test fnv_manual   ... bench:  39,413,669 ns/iter (+/- 22,134,246)
test std_entry    ... bench:  68,217,384 ns/iter (+/- 32,603,154)
test std_manual   ... bench:  86,265,556 ns/iter (+/- 32,434,485)
```

However, I think that there is still some improvement, at least for the `VacantEntry` case. (But I only skimmed the code, so I might be very wrong). In this line:

```rust
map.entry(key).or_insert_with(|| produce_value())
```

Let's assume `key` is not yet in the map.

First [`entry`](https://github.com/Amanieu/hashbrown/blob/master/src/map.rs#L567-L582) is called. It calculates the hash, performs the lookup and creates a corresponding `Entry` value. Then, [`or_insert_with`](https://github.com/Amanieu/hashbrown/blob/master/src/map.rs#L1513-L1518) is executed (which basically only calls [`VacantEntry::insert`](https://github.com/Amanieu/hashbrown/blob/master/src/map.rs#L1882-L1889)). This leads to [`RawTable::insert`](https://github.com/Amanieu/hashbrown/blob/master/src/raw/mod.rs#L636-L653). And here is where I think redundant work is done: this last `insert` function performs the lookup again. The hash is only calculated once, because it is stored in `VacantEntry`. But couldn't the bucket index also be stored in `VacantEntry`?  That way the insert operation wouldn't need to search for a slot to insert. Right?

Or is it just not worth it caching the index? I only have limited knowledge of the underlying data structure :/

Anyway, thanks again!

**Comment by Amanieu** [comment]
This is not possible because of the way lookups work. Since we scan groups of 16 elements in parallel using SIMD, we don't get a bucket index when a lookup fails. We have to perform a second scan which looks for slots that are either `EMPTY` or `DELETED`.

**Comment by LukasKalbertodt** [comment]
Ah ok, that makes sense. Thank you :)
