### ISSUE TITLE
Support for the raw_entry API

### ISSUE THREAD

**Issue by thomcc** [Amanieu/hashbrown#23]
This isn't yet part of `std::collections::HashMap`'s API, but has a number of features that cannot be done in the current API. It would be extremely nice if these could be done with hashbrown.

For background, see:

- Raw entry Pre-RFC: https://internals.rust-lang.org/t/pre-rfc-abandonning-morals-in-the-name-of-performance-the-raw-entry-api/7043
- And the rust-lang PR: https://github.com/rust-lang/rust/pull/54043

**Comment by Amanieu** [comment]
map.rs in hashbrown is pretty much a straight copy & paste of map.rs from the standard library, so porting raw_entry should be trivial.

**Comment by Amanieu** [comment]
There is a slight issue, see [my comment](https://github.com/rust-lang/rust/issues/56167#issuecomment-441711468).
