### ISSUE TITLE
Add memory usage info to the readme

### ISSUE THREAD

**Issue by matklad** [Amanieu/hashbrown#24]
Hi!

It would be useful to have a rough idea about relative memory usage of hashbrown and rustc_hash!

If hashbrown is 2x faster and the same size, it is super cool
If, for example, it is 2x faster but 2x larger, that it is also very cool, but might not fit some projects.

**Comment by Amanieu** [comment]
The memory usage is actually smaller than the standard hash map, since we only store 1 byte of overhead per bucket instead of 8 bytes. The load factor is slightly lower (87.5% instead of 90.9%) but this should hardly make a difference in practice.
