### ISSUE TITLE
meow

### ISSUE THREAD

**Issue by killercup** [Amanieu/hashbrown#34]
I have recently come aross two different interesting projects that did… well "did something with hashes". [meowhash](https://mollyrocket.com/meowhash) and this crate. Now, I have seen thah hashbrown uses FxHash by default, and that it also uses SIMD tricks to speed up lookup. Meow is a hashing algorithm that also extensively uses SIMD and that is apparently very fast.

I have very limited knowledge of how this all works, so maybe it's obviously stupid. But: Would it be interesting to combine the two?

There is a port of Meow to Rust [here](https://github.com/bodil/meowhash-rs) but from quickly glancing at it, it doesn't seem to support `std::hash::Hasher` and it might also be difficult to do so as it seems to need to reset some internal data when you'd call `finish(&self)`.

**Comment by Amanieu** [comment]
Unfortunately MeowHash isn't exactly suitable for use in a hash table. There are actually two main categories of hash functions:

- Hash functions for large blocks of data (e.g. whole files), such as MD5, SHA1. These tend to generate large hash values, e.g. 128/256/512 bits. 
- Hash functions for small keys (e.g. `u32`, a short string). These will generate 32/64-bit hash values, which is sufficient for use in a hash table.

MeowHash is of the first type. In fact SIMD acceleration is only really useful for hashing large blocks of data.

**Comment by killercup** [comment]
Yeah, that makes sense. I wasn't sure what "large data" meant -- larger than 16 bytes (it generates 128 bits of hash value already) or larger than 16kB. Especially this quote from the post lead me to open this issue:

> It has also now been tuned to be the fastest hash on small inputs, too. Despite the fact that it is a full 128-bit hash, it still outperforms “fast” 64-bit hashes across all input sizes. So whether you have data buffers of a few bytes or a few gigabytes, Meow is the fastest hash available.
