### ISSUE TITLE
Optimization in is_full()

### ISSUE THREAD

**Issue by leventov** [Amanieu/hashbrown#36]
https://github.com/Amanieu/hashbrown/blob/63aa152cfd3b3690b69c3f8afd14f4904edb38cf/src/raw/mod.rs#L54-L56

`(ctrl as i8) >= 0` might be faster because might benefit the sign bit already set (if LLVM doesn't perform this optimization automatically).

**Comment by Amanieu** [comment]
LLVM seems to generate the same assembly code in both cases.
