### ISSUE TITLE
Support retrieving an arbitrary element

### ISSUE THREAD

**Issue by jonhoo** [Amanieu/hashbrown#43]
This may be an exceptionally niche use-case but I figured I'd bring it up anyway. In [Noria](https://github.com/mit-pdos/noria), we use a hash table as a sort of cache, and occasionally we want to evict a _random_ element from the map. Unfortunately, there is no good way of getting that efficiently (in `hashbrown` or in `std::HashMap`). `map.keys().skip(rand(map.len()))` for example is far too slow. @fintelia has a fork of `std::HashMap` in [`rahashmap`](https://github.com/fintelia/rahashmap) that we're using, and it:

 - Exposes [`raw_capacity`](https://github.com/fintelia/rahashmap/commit/cd58a4e45eb7c1467d4e7ed723ffce1d9f2030b1)
 - Adds [`remove_element_at_index`](https://github.com/fintelia/rahashmap/commit/cd4ee519081cb799f9c3dd229b2063cc62248eeb)
 - Adds [`at_index`](https://github.com/fintelia/rahashmap/commit/34b61059dc0fbcae0c112d71e9d89e122909b55d)

Together, these three operations let us efficiently find a random key/value pair in a map. I realize that this may be fair more internals than you'd like to expose, but _some_ way of getting at/removing a random element would be really handy, as I don't think there's currently a way of doing it through the normally-exposed APIs. Is there any avenue whereby you could imagine a use-case like this being supported? I was toying with the idea of (ab)using [`RawEntryBuilder::from_hash`](https://docs.rs/hashbrown/0.1.8/hashbrown/hash_map/struct.RawEntryBuilder.html#method.from_hash), but guessing a hash is very unlikely to yield anything useful, so I think that's out...

**Comment by jonhoo** [comment]
cc @ms705

**Comment by Amanieu** [comment]
As you said, this is a very niche use case and I don't think that it is appropriate to support this API in hashbrown. Have you considered using `IndexMap` which does support your use case?

**Comment by fintelia** [comment]
Another option is to keep a long lived fork of hashbrown, which I think would be much less painful than a fork of the standard library. The standard hashmap uses a ton of unstable features, including a couple compiler internal features. My fork could thus only run on nightly and even then frequently breaks without warning because of some compiler change. The only way I've stood a chance at keeping it working was to signup for notification emails any time there was a change to the hash_map directory in the main Rust repository.

To me this points to a broader point that the standard library is too tightly coupled to the compiler. hashbrown gets _better_ performance despite not relying on these internal features.

**Comment by jonhoo** [comment]
@Amanieu unfortunately it's a little complicated by the fact that we are accessing the map through [`evmap`](https://github.com/jonhoo/rust-evmap), and I don't think `evmap` will want to switch from `hashbrown` to `IndexMap`... That said, maybe the trick will be to somehow make `evmap` generic over the underlying map (if that doesn't require higher-kinded trait bounds that is)... Thanks anyway!

**Comment by jonhoo** [comment]
An alternative here I suppose is to emulate Python's [`dict::popitem`](https://docs.python.org/3/library/stdtypes.html#dict.popitem) which just removes and returns an arbitrary `(key, value)`. This has the added benefit that you can do things like:
```rust
while let Some((key, value)) = map.popitem() {
    // ...
    map.insert(key2, value2);
}
```
The downside though is that if it removes, say, the first item by hash value, it will always remove the same key if you re-insert it, which makes it a poor choice for eviction. One workaround for that might be to remove the first element _following a random starting position_.

**Comment by jonhoo** [comment]
Just for completeness and for others looking at this, this ties in to https://github.com/rust-lang/rust/issues/27804 and https://github.com/rust-lang/rfcs/issues/1800
