### ISSUE TITLE
rayon

### ISSUE THREAD

**Issue by vchugreev** [Amanieu/hashbrown#49]
Many thanks for the library!
Unfortunately, library does not work along with the rayon. What am I doing wrong?

```
use hashbrown::HashMap;
use rayon::prelude::*;

fn main() {
    let mut test = HashMap::new();
    test.insert("1", 1);
    test.insert("2", 2);
    test.insert("3", 3);
    let vec: Vec<usize> = test.par_iter().map(|(_, val)| *val).collect();
    println!("len: {}", vec.len());
}
```
```
error[E0599]: no method named `par_iter` found for type `hashbrown::map::HashMap<&str, {integer}>` in the current scope
  --> src\main.rs:10:32
   |
10 |     let vec: Vec<usize> = test.par_iter().map(|(_, val)| *val).collect();
   |                                ^^^^^^^^
   |
   = note: the method `par_iter` exists but the following trait bounds were not satisfied:
           `hashbrown::map::HashMap<&str, {integer}> : rayon::iter::IntoParallelRefIterator`

error: aborting due to previous error
```

Cargo.toml
```
[dependencies]
hashbrown = "0.1.8"
rayon = "1.0.3"
```
cargo 1.34.0-nightly (5c6aa46e6 2019-02-22)

**Comment by Amanieu** [comment]
You need to enable the `rayon` feature in Cargo.toml:

```
hashbrown = { version = "0.1.8", features = ["rayon"] }
```

**Comment by vchugreev** [comment]
Excellent! It works. Thanks for the help.
Maybe it is worth adding this to the documentation?

**Comment by Amanieu** [comment]
Feel free to open a PR with documentation updates!

**Comment by vchugreev** [comment]
I don't really understand this (github workflow) :) Thanks again!

**Comment by Amanieu** [comment]
You can do it from the website, just go to README.md and click on the button to edit the file.

**Comment by vchugreev** [comment]
Is done. Sorry for any errors, English is not native to me.

**Comment by CryZe** [comment]
You stil need to open a Pull Request for the changes. There should be a button or something for creating a Pull Request here: https://github.com/vchugreev/hashbrown/tree/patch-1

**Comment by vchugreev** [comment]
CryZe, thanks!
