### ISSUE TITLE
Implement Hash for collections

### ISSUE THREAD

**Issue by StevenDoesStuffs** [Amanieu/hashbrown#59]
Is it possible to implement Hash on the hashmap or hashset? 
I know that rust stdlib doesn't do this for security reasons. See https://github.com/rust-lang/rust/issues/21182
But as it seems like the goal of this library isn't as focused on security (y'all are using fxhash) as much the stdlib HashSet is, that shouldn't be an issue.

**Comment by Amanieu** [comment]
Unfortunately this is not possible because the ordering of the elements in a `HashMap` is non-deterministic but the hash value depends on the ordering. This means that two `HashMap`s with the same contents may have different hashes because the elements are in a different order internally.

**Comment by StevenDoesStuffs** [comment]
Actually, you can use a commutative operator to put together the hash of the hashmap given the hashes of the keys and values. I know that other languages do this, so it's definitely not impossible.
