### ISSUE TITLE
Hashes are assumed to be only usize

### ISSUE THREAD

**Issue by cuviper** [Amanieu/hashbrown#60]
`h1` will fail on 32-bit targets if a hasher yields a `u64` greater than `u32::MAX`:
https://github.com/Amanieu/hashbrown/blob/9068eb7a2268d879dc4453ac72238e8a992f1469/src/raw/mod.rs#L120-L126

The comment in `h2` gives some insight to this, but that **only** applies to `FxHash`:
https://github.com/Amanieu/hashbrown/blob/9068eb7a2268d879dc4453ac72238e8a992f1469/src/raw/mod.rs#L131-L138

See also the failure in https://github.com/rust-lang/rust/pull/58623#issuecomment-482373125

**Comment by Amanieu** [comment]
Yes, this assert was mistakenly added as part of the clippy support, it should be removed.

**Comment by cuviper** [comment]
Are there any tests using alternate hashes? Even `RandomState` should trigger this.

**Comment by gnzlbg** [comment]
Replacing the assert with a comment explaining why the truncation is ok and adding a test that triggers this sounds good to me.

**Comment by gnzlbg** [comment]
Is there an issue open to add a test for this ?

**Comment by Amanieu** [comment]
Tests were added in #63.

**Comment by gnzlbg** [comment]
Awesome, thank you both for fixing this, and sorry that I broke it!
