### ISSUE TITLE
Expose the hasher algorithm and type aliases for `HashMap`, `HashSet` and `BuildHasher`

### ISSUE THREAD

**Issue by hcpl** [Amanieu/hashbrown#9]
As I understand the purpose of this crate, the only thing that is different from `std::collections::Hash{Map, Set}` and other hash-based data structures from other crates is a different hasher. If that is not true, then what I'm saying below is unapplicable, so feel free to close.

The goal is to eliminate the need to maintain a separate `Hash{Map, Set}` and also reuse impls for `Hash{Map, Set}` defined in other crates (provided that they are generic over the hasher) so that we don't have to provide them either.

For example, that's how both [`fxhash`](https://docs.rs/fxhash/0.2.1/fxhash/) and [`fnv`](https://docs.rs/fnv/1.0.6/fnv/) do:
* [`FxHashMap`](https://docs.rs/fxhash/0.2.1/fxhash/type.FxHashMap.html) and [`FnvHashMap`](https://docs.rs/fnv/1.0.6/fnv/type.FnvHashMap.html);
* [`FxHashSet`](https://docs.rs/fxhash/0.2.1/fxhash/type.FxHashSet.html) and [`FnvHashSet`](https://docs.rs/fnv/1.0.6/fnv/type.FnvHashSet.html);
* [`FxBuildHasher`](https://docs.rs/fxhash/0.2.1/fxhash/type.FxBuildHasher.html) and [`FnvBuildHasher`](https://docs.rs/fnv/1.0.6/fnv/type.FnvBuildHasher.html).

This is technically a breaking change since the semantics of `hashbrown::HashMap` and `hashbrown::HashSet` might be altered in some ways (that I don't know of, unfortunately).

Solving this issue will help solving https://github.com/Amanieu/hashbrown/issues/6 as well.

**Comment by Amanieu** [comment]
Actually `hashbrown` is a re-implementation of the underlying hash table based on Google's SwissTable design. It uses `FxHash` as the default hasher.

**Comment by hcpl** [comment]
Oh, so I got it backwards. How about generalizing `hashbrown` for different hashers then?

Also it might be useful to change the docs a little bit, because "Drop-in replacement for the standard library `HashMap` and `HashSet` types" made me think of "a new hasher for standard `HashMap` and `HashSet`", not "new `HashMap` and `HashSet` implementations altogether".
